#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-activemodel
Version  : 4.2.3
Release  : 9
URL      : https://rubygems.org/downloads/activemodel-4.2.3.gem
Source0  : https://rubygems.org/downloads/activemodel-4.2.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= Active Model -- model interfaces for Rails
Active Model provides a known set of interfaces for usage in model classes.
They allow for Action Pack helpers to interact with non-Active Record models,
for example. Active Model also helps with building custom ORMs for use outside of
the Rails framework.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n activemodel-4.2.3
gem spec %{SOURCE0} -l --ruby > rubygem-activemodel.gemspec

%build
gem build rubygem-activemodel.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
activemodel-4.2.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/activemodel-4.2.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/conversion.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/dirty.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/forbidden_attributes_protection.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/gem_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/lint.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/locale/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/model.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/naming.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/secure_password.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/serialization.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/serializers/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/serializers/xml.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/test_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/translation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/absence.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/acceptance.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/clusivity.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/confirmation.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/exclusion.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/format.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/inclusion.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/length.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/numericality.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/presence.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/validates.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validations/with.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/activemodel-4.2.3/lib/active_model/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/activemodel-4.2.3.gemspec
